### ISSUE TITLE
Mongoose population?

### ISSUE THREAD

**Issue by viztastic** [sarkistlt/mongoose-schema-to-graphql#2]
Hi @sarkistlt 

Great module, thanks! 

Does your module support mongoose document population? 
How does this compare to the mongoose-graffiti module in your opinion?

**Comment by sarkistlt** [comment]
Thank you. Yes it does. I can't comment about mongoose-graffiti, just because never worked with that module and time when I released this module I didn't heard anything about mongoose-graffiti, and couldn't find any similar tool to generate GraphQL Types. That was the main reason why I build this package. 

You can check both and see which one works better for you. 
This module pretty easy and stable to use, that's all I can say. Good luck!
